/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.Pelicula;
import java.sql.Date;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Calendar;

/**
 *
 * @author fernando
 */
public class JfrmUpdate extends javax.swing.JFrame {

    /**
     * Creates new form JfrmIngresar
     */
    private String categoria;
    private String formato;

    public JfrmUpdate() {

        initComponents();
        this.jcmb_categoria.setEnabled(false);
        this.jDateChooser1.setEnabled(false);
        this.jcmb_formato.setEnabled(false);
        this.jtxt_diasPrestamo.setEnabled(false);
        this.jtxt_nombre.setEnabled(false);
        java.util.Date ultilDate = new java.util.Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(ultilDate);
        cal.set(Calendar.MILLISECOND, 0);
        this.jDateChooser1.setCalendar(cal);
        this.jDateChooser1.setEnabled(false);
//this.jcmb_categoria.setSelectedIndex(0);
        //this.jcmb_formato.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jbtn_update = new javax.swing.JButton();
        jtxt_codigo = new javax.swing.JTextField();
        jtxt_nombre = new javax.swing.JTextField();
        jcmb_categoria = new javax.swing.JComboBox();
        jtxt_diasPrestamo = new javax.swing.JTextField();
        jcmb_formato = new javax.swing.JComboBox();
        jbtn_buscar = new javax.swing.JButton();
        jbtn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDateChooser1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jDateChooser1ComponentAdded(evt);
            }
        });
        jDateChooser1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDateChooser1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyPressed(evt);
            }
        });

        jbtn_update.setText("Modificar");
        jbtn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_updateActionPerformed(evt);
            }
        });

        jtxt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_codigoActionPerformed(evt);
            }
        });

        jtxt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreActionPerformed(evt);
            }
        });

        jcmb_categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "estreno", "normal", "recuerdo" }));
        jcmb_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_categoriaActionPerformed(evt);
            }
        });

        jcmb_formato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DVD", "Blue Ray Disc", "VHS" }));
        jcmb_formato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_formatoActionPerformed(evt);
            }
        });

        jbtn_buscar.setText("Buscar");
        jbtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarActionPerformed(evt);
            }
        });

        jbtn_delete.setText("Eliminar");
        jbtn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxt_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jcmb_categoria, javax.swing.GroupLayout.Alignment.LEADING, 0, 87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtxt_diasPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jtxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcmb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(93, 93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_diasPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcmb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_update))
                        .addGap(26, 26, 26)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn_delete))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDateChooser1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDateChooser1AncestorAdded
        // TODO add your handling code here:


    }//GEN-LAST:event_jDateChooser1AncestorAdded

    private void jDateChooser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1KeyPressed

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void jDateChooser1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jDateChooser1ComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser1ComponentAdded

    private void jbtn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_updateActionPerformed
        // TODO add your handling code here:
        Pelicula p1 = new Pelicula();
        Pelicula p = new Pelicula(this.jtxt_codigo.getText().toLowerCase(),
                this.jtxt_nombre.getText().toLowerCase(),
                this.categoria.toLowerCase(),
                Integer.parseInt(this.jtxt_diasPrestamo.getText()),
                this.formato.toLowerCase(),
                new java.sql.Timestamp(this.jDateChooser1.getDate().getTime()));
        p1.update(p);
    }//GEN-LAST:event_jbtn_updateActionPerformed

    private void jtxt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_codigoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtxt_codigoActionPerformed

    private void jtxt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombreActionPerformed

    private void jcmb_formatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_formatoActionPerformed
        // TODO add your handling code here:
        switch (this.jcmb_formato.getSelectedIndex()) {
            case 0:
                this.formato = "dvd";
                break;
            case 1:
                this.formato = "blue ray disc";
                break;
            case 2:
                this.formato = "vhs";
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jcmb_formatoActionPerformed

    private void jcmb_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_categoriaActionPerformed
        // TODO add your handling code here:
        switch (this.jcmb_categoria.getSelectedIndex()) {
            case 0:
                this.categoria = "estreno";
                break;
            case 1:
                this.categoria = "normal";
                break;
            case 2:
                this.categoria = "recuerdo";
                break;
            default:
            //throw new AssertionError();
        }
    }//GEN-LAST:event_jcmb_categoriaActionPerformed

    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
        // TODO add your handling code here:
        Pelicula p = new Pelicula().verPorCode(this.jtxt_codigo.getText().toLowerCase());
        if (p != null) {
            this.jtxt_nombre.setEnabled(true);
            this.jtxt_nombre.setText(p.getNombre());
            this.jtxt_diasPrestamo.setEnabled(true);
            this.jtxt_diasPrestamo.setText(String.valueOf(p.getDiasPrestamo()));
            
            this.jcmb_categoria.setEnabled(true);
            this.jcmb_categoria.setSelectedIndex(p.getCategoria().equalsIgnoreCase("estreno")?0:
                    p.getCategoria().equalsIgnoreCase("normal")?1:
                            p.getCategoria().equalsIgnoreCase("recuerdo")?2:0);
            this.jbtn_update.setEnabled(true);
            this.jcmb_formato.setEnabled(true);
            this.jcmb_formato.setSelectedIndex(p.getFormato().equalsIgnoreCase("dvd")?0:
                    p.getFormato().equalsIgnoreCase("blue ray disc")?1:
                            p.getFormato().equalsIgnoreCase("vhs")?2:0);
            this.jDateChooser1.setEnabled(true);
            this.jDateChooser1.setDate(p.getFechaIngreso());
        }

    }//GEN-LAST:event_jbtn_buscarActionPerformed

    private void jbtn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_deleteActionPerformed
        // TODO add your handling code here:
        new Pelicula().delete(this.jtxt_codigo.getText());
        if (new Pelicula().verPorCode(this.jtxt_codigo.getText().toLowerCase())==null) {
            this.jcmb_categoria.setEnabled(false);
        this.jDateChooser1.setEnabled(false);
        this.jcmb_formato.setEnabled(false);
        this.jtxt_diasPrestamo.setEnabled(false);
        this.jtxt_nombre.setEnabled(false);
        java.util.Date ultilDate = new java.util.Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(ultilDate);
        cal.set(Calendar.MILLISECOND, 0);
        this.jDateChooser1.setCalendar(cal);
        this.jDateChooser1.setEnabled(false);
            
        }
    }//GEN-LAST:event_jbtn_deleteActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JfrmUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JfrmUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JfrmUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JfrmUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JfrmUpdate().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JButton jbtn_buscar;
    private javax.swing.JButton jbtn_delete;
    private javax.swing.JButton jbtn_update;
    private javax.swing.JComboBox jcmb_categoria;
    private javax.swing.JComboBox jcmb_formato;
    private javax.swing.JTextField jtxt_codigo;
    private javax.swing.JTextField jtxt_diasPrestamo;
    private javax.swing.JTextField jtxt_nombre;
    // End of variables declaration//GEN-END:variables

   
}
